// Mapa simples de códigos ISO 639-1 -> nome em PT-BR (subset comum).
export const LANG_LABEL: Record<string, string> = {
  pt: "Português",
  en: "Inglês",
  es: "Espanhol",
  ja: "Japonês",
  ko: "Coreano",
  zh: "Chinês",
  fr: "Francês",
  de: "Alemão",
  it: "Italiano",
  ru: "Russo",
  ar: "Árabe",
  hi: "Hindi",
  tr: "Turco",
  pl: "Polonês",
  nl: "Holandês",
  sv: "Sueco",
  no: "Norueguês",
  da: "Dinamarquês",
  fi: "Finlandês",
  cs: "Tcheco",
  el: "Grego",
  he: "Hebraico",
  th: "Tailandês",
  id: "Indonésio",
  vi: "Vietnamita",
  uk: "Ucraniano",
  hu: "Húngaro",
  ro: "Romeno",
  ca: "Catalão",
};
